apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
